name: CI

on: [push, pull_request]

jobs:
  # C_test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]

  #   runs-on: ${{ matrix.os }}
  #   timeout-minutes: 30

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v6.0.2

  #   - name: Install C dependencies (Ubuntu)
  #     if: matrix.os == 'ubuntu-latest'
  #     run: |
  #       sudo apt-get remove needrestart
  #       sudo apt-get update
  #       sudo apt-get install -y cmake

  #   - name: Build C code
  #     run: |
  #       mkdir -p build
  #       cd build
  #       cmake ..
  #       make

  #   - name: Run C tests
  #     run: |
  #       cd build
  #       ctest

  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.2
    - name: Run Ruff linter on Python code
      uses: astral-sh/ruff-action@v4.0.0
      with:
        args: "check"
      continue-on-error: true
    - name: Check code formatting
      uses: astral-sh/ruff-action@v4.0.0
      with:
        args: "format --check"
      continue-on-error: true

  TypeCheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Run ty
        run: uvx ty check
        continue-on-error: true
  Test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --group dev
      - run: uv run pytest
