name: CI

on: [push, pull_request]

jobs:
  C_test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.2

    - name: Install C dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get remove needrestart
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build C code
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run C tests
      run: |
        cd build
        ctest

  Pylint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 mypy black
          python -c "import black, flake8, mypy, pylint; print('All imports OK')"

      # - name: Check Python code formatting
      #   run: |
      #     black ./src/

      - name: Run Python linter
        run: |
          flake8 ./src/
        continue-on-error: true

      - name: Run python lint score
        run: |
          pylint --max-line-length=150 ./src/
        continue-on-error: true

      - name: Run Python type checking
        run: |
          mypy ./src/
        continue-on-error: true
